# .github/workflows/deploy.yml
name: Deploy Backend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy en VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          port: 22
          script: |
            # Entrar al directorio del proyecto en la VPS
            cd /opt/app/dap_depot_management_services

            # Asegurarse de que el repo esté actualizado
            git reset --hard
            git pull origin main

            # Dar permisos al wrapper de Gradle
            chmod +x ./gradlew

            # Construir la aplicación (jar) sin test
            ./gradlew build -x test

            # Construir imagen Docker usando Dockerfile y docker-compose.yml
            docker compose build

            # Bajar contenedores antiguos
            docker compose down

            # Levantar contenedores usando el .env existente
            docker compose up -d
          timeout: 20m